### ISSUE TITLE
connection with srv

### ISSUE THREAD

**Issue by Asmau1234** [borice/play-reactivemongo-atlas#1]
Were you ever able to connect to an atlas cluster using srv connection string format?? I came across this project while encountering the issue  stated in this project.

**Comment by borice** [comment]
Yes, it works fine for me.  The connection string I use looks like this:
`mongodb+srv://username:password@my-atlas-qfedj.mongodb.net/mydb?retryWrites=true`

**Comment by Asmau1234** [comment]
I have the same format in my application conf file but it keeps returning a `MongoError['No primary node is available! (Supervisor-15/Connection-16)']  ` Is there some special configuration I need to do? I was able to access the cluster via the Mongo shell with the same format but reactivemongo just keeps flagging the mongoerror above. I am running scala 2.12 and reactivemongo 0.12.6.
`mongodb.uri = "mongodb+srv://password@my-cluster.abo25.mongodb.net/my-db?retryWrites=true&w=majority"`

**Comment by borice** [comment]
You don't seem to provide the `username`:`password` format that my connection shows. Unless by "password" you mean the same format I showed.

Also, what are you using ReactiveMongo from? Play?

**Comment by Asmau1234** [comment]
Sorry that is a typo. I have the username and password in the same format as yours. Yes, Play.

**Comment by borice** [comment]
And you've whitelisted the IP address (in Atlas) of the machine where your code is running?

**Comment by Asmau1234** [comment]
I have whitelisted my IP and in fact, Allowed all IPs.

0.0.0.0/0  (includes your current IP address) | Allow all

**Comment by borice** [comment]
I don't know then -- create a the smallest project possible that reproduces the problem, put it on github, and send the link on the ReactiveMongo google group (where I saw you already posted your problem) so that people can take a look at your code and see what's wrong.

**Comment by Asmau1234** [comment]
I'll do that. Thanks for the response.
